-- CREATE TABLE tccmatch_user
-- (
--     id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
--     full_name VARCHAR(255),
--     email     VARCHAR(255),
--     username  VARCHAR(255),
--     password  VARCHAR(255),
--     role      INTEGER,
--     CONSTRAINT pk_tccmatchuser PRIMARY KEY (id)
-- );
--
-- CREATE TABLE student
-- (
--     id                       BIGINT NOT NULL,
--     registration             VARCHAR(255),
--     expected_conclusion_term VARCHAR(255),
--     tcc_id                   BIGINT,
--     CONSTRAINT pk_student PRIMARY KEY (id)
-- );
--
-- CREATE TABLE professor
-- (
--     id    BIGINT NOT NULL,
--     quota INTEGER,
--     CONSTRAINT pk_professor PRIMARY KEY (id)
-- );
--
-- CREATE TABLE admin
-- (
--     id BIGINT NOT NULL,
--     CONSTRAINT pk_admin PRIMARY KEY (id)
-- );
--
-- CREATE TABLE tccproposal
-- (
--     id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
--     title       VARCHAR(255),
--     description VARCHAR(255),
--     tcc_status  INTEGER,
--     student_id  BIGINT,
--     CONSTRAINT pk_tccproposal PRIMARY KEY (id)
-- );
--
-- CREATE TABLE tcc
-- (
--     id           BIGINT NOT NULL,
--     professor_id BIGINT,
--     CONSTRAINT pk_tcc PRIMARY KEY (id)
-- );
--
-- CREATE TABLE orientation_interest
-- (
--     id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
--     interested_student_id BIGINT,
--     interestedtcc_id      BIGINT,
--     CONSTRAINT pk_orientationinterest PRIMARY KEY (id)
-- );
--
-- CREATE TABLE orientation_issue
-- (
--     id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
--     related_issue VARCHAR(255),
--     student_id    BIGINT,
--     tcc_id        BIGINT,
--     CONSTRAINT pk_orientationissue PRIMARY KEY (id)
-- );
--
-- CREATE TABLE orientation_proposal
-- (
--     id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
--     interested_professor_id BIGINT,
--     interested_proposal_id  BIGINT,
--     CONSTRAINT pk_orientationproposal PRIMARY KEY (id)
-- );
--
-- CREATE TABLE professor_labs
-- (
--     id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
--     professor_id BIGINT,
--     labs          VARCHAR(255),
--     CONSTRAINT pk_professor_labs PRIMARY KEY (id)
-- );

CREATE TABLE TCCPROPOSAL(
                              ID BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                              DESCRIPTION VARCHAR(255),
                              TCC_STATUS INTEGER,
                              TITLE VARCHAR(255),
                              STUDENT_ID BIGINT
);

CREATE TABLE PROFESSOR_INTERESTED_STUDY_AREAS(
                                                   PROFESSOR_ID BIGINT NOT NULL,
                                                   STUDY_AREA_ID BIGINT NOT NULL
);

CREATE TABLE PROFESSOR_INTERESTEDTCCS(
                                           PROFESSOR_ID BIGINT NOT NULL,
                                           INTERESTEDTCCS_ID BIGINT NOT NULL
);

CREATE TABLE PROFESSOR_LABS(
                                 PROFESSOR_ID BIGINT NOT NULL,
                                 LABS VARCHAR(255)
);

CREATE TABLE PROFESSOR_ORIENTEDTCCS(
                                         PROFESSOR_ID BIGINT NOT NULL,
                                         ORIENTEDTCCS_ID BIGINT NOT NULL
);

CREATE TABLE STUDENT(
                          EXPECTED_CONCLUSION_TERM VARCHAR(255),
                          REGISTRATION VARCHAR(255),
                          ID BIGINT GENERATED BY DEFAULT AS IDENTITY,
                          TCC_ID BIGINT
);

CREATE TABLE PROFESSOR(
                            QUOTA INTEGER,
                            ID BIGINT GENERATED BY DEFAULT AS IDENTITY
);

CREATE TABLE ORIENTATION_PROPOSAL(
                                       ID BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                       INTERESTED_PROFESSOR_ID BIGINT,
                                       INTERESTED_PROPOSAL_ID BIGINT
);

CREATE TABLE ORIENTATION_ISSUE(
                                    ID BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                    RELATED_ISSUE VARCHAR(255),
                                    STUDENT_ID BIGINT,
                                    TCC_ID BIGINT
);

CREATE TABLE ORIENTATION_INTEREST(
                                       ID BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                       INTERESTED_STUDENT_ID BIGINT,
                                       INTERESTEDTCC_ID BIGINT
);

CREATE TABLE ADMIN(
    ID BIGINT GENERATED BY DEFAULT AS IDENTITY
);

CREATE TABLE STUDENT_INTERESTED_STUDY_AREAS(
                                                 STUDENT_ID BIGINT NOT NULL,
                                                 STUDY_AREA_ID BIGINT NOT NULL
);

CREATE TABLE STUDY_AREA(
                             ID BIGINT GENERATED BY DEFAULT AS IDENTITY,
                             DESCRIPTION VARCHAR(255)
);

CREATE TABLE TCC(
                      ID BIGINT GENERATED BY DEFAULT AS IDENTITY,
                      PROFESSOR_ID BIGINT
);

CREATE TABLE TCCMATCH_USER(
                                ID BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                EMAIL VARCHAR(255),
                                FULL_NAME VARCHAR(255),
                                PASSWORD VARCHAR(255),
                                ROLE INTEGER,
                                USERNAME VARCHAR(255)
);

CREATE TABLE TCCPROPOSAL_STUDY_AREAS(
                                          TCCPROPOSAL_ID BIGINT NOT NULL,
                                          STUDY_AREAS_ID BIGINT NOT NULL
);