ALTER TABLE TCCMATCH_USER
    ADD CONSTRAINT CONSTRAINT_C PRIMARY KEY(ID);

ALTER TABLE TCC
    ADD CONSTRAINT CONSTRAINT_1 PRIMARY KEY(ID);

ALTER TABLE STUDY_AREA
    ADD CONSTRAINT CONSTRAINT_2 PRIMARY KEY(ID);

ALTER TABLE STUDENT_ORIENTATION_INTERESTS
    ADD CONSTRAINT CONSTRAINT_3B PRIMARY KEY(INTERESTED_STUDENT_ID, TCC_ID);

ALTER TABLE STUDENT_INTERESTED_STUDY_AREAS
    ADD CONSTRAINT CONSTRAINT_4B PRIMARY KEY(STUDENT_ID, STUDY_AREA_ID);

ALTER TABLE STUDENT
    ADD CONSTRAINT CONSTRAINT_B PRIMARY KEY(ID);

ALTER TABLE PROFESSOR_REGISTEREDTCCS
    ADD CONSTRAINT CONSTRAINT_4E PRIMARY KEY(PROFESSOR_ID, REGISTEREDTCCS_ID);

ALTER TABLE PROFESSOR_INTERESTEDTCCS
    ADD CONSTRAINT CONSTRAINT_4 PRIMARY KEY(PROFESSOR_ID, INTERESTEDTCCS_ID);

ALTER TABLE PROFESSOR
    ADD CONSTRAINT CONSTRAINT_6 PRIMARY KEY(ID);

ALTER TABLE ORIENTATION_ISSUE
    ADD CONSTRAINT CONSTRAINT_E PRIMARY KEY(ID);

ALTER TABLE ADMIN
    ADD CONSTRAINT CONSTRAINT_3 PRIMARY KEY(ID);

ALTER TABLE PROFESSOR_INTERESTEDTCCS
    ADD CONSTRAINT UK_R286TXHWDQT8QM4EXRA9UMQ5J UNIQUE(INTERESTEDTCCS_ID);

ALTER TABLE PROFESSOR_REGISTEREDTCCS
    ADD CONSTRAINT UK_F8DE6RJ8DCL7MFS58TU3SUJG3 UNIQUE(REGISTEREDTCCS_ID);

ALTER TABLE TCC_INTERESTED_PROFESSORS
    ADD CONSTRAINT FK7MOIKWVVEW2D97VIJERUHF02Y FOREIGN KEY(TCC_ID) REFERENCES TCC(ID) ;

ALTER TABLE TCC_STUDY_AREAS
    ADD CONSTRAINT FK8M8VU79K3JIJVY77SC3VLRIHW FOREIGN KEY(STUDY_AREA_ID) REFERENCES STUDY_AREA(ID) ;

ALTER TABLE STUDENT_ORIENTATION_INTERESTS
    ADD CONSTRAINT FK3Y50C4RK638JOWFQ5DOKQM41J FOREIGN KEY(TCC_ID) REFERENCES TCC(ID) ;

ALTER TABLE TCC_STUDY_AREAS
    ADD CONSTRAINT FK8HSWXQ4BIMTHRDEYW98FO3XYM FOREIGN KEY(TCC_ID) REFERENCES TCC(ID) ;

ALTER TABLE TCC_INTERESTED_STUDENTS
    ADD CONSTRAINT FKJ4V012N56R6SHRPDT5JM8MGWT FOREIGN KEY(STUDENT_ID) REFERENCES STUDENT(ID) ;

ALTER TABLE ORIENTATION_ISSUE
    ADD CONSTRAINT FKGL1IRLNUE2R6U2YHNVDYJL2R4 FOREIGN KEY(TCCMATCH_USER_ID) REFERENCES TCCMATCH_USER(ID) ;

ALTER TABLE STUDENT_ORIENTATION_INTERESTS
    ADD CONSTRAINT FKFITC9QKI4OPTHJWY5VPV3P8T5 FOREIGN KEY(INTERESTED_STUDENT_ID) REFERENCES STUDENT(ID) ;

ALTER TABLE ORIENTATION_ISSUE
    ADD CONSTRAINT FKPUPU6PN14WAOS05YNI6OOVG7N FOREIGN KEY(TCC_ID) REFERENCES TCC(ID) ;

ALTER TABLE PROFESSOR_INTERESTEDTCCS
    ADD CONSTRAINT FKRDEQXIIM8VS6DL1P0HICUXRB9 FOREIGN KEY(INTERESTEDTCCS_ID) REFERENCES TCC(ID) ;

ALTER TABLE PROFESSOR_INTERESTEDTCCS
    ADD CONSTRAINT FKAL6527JR7JXUKHKJP8NV5T0P0 FOREIGN KEY(PROFESSOR_ID) REFERENCES PROFESSOR(ID) ;

ALTER TABLE STUDENT_INTERESTED_STUDY_AREAS
    ADD CONSTRAINT FK2M9QWOB07JNNPYRHAG6S22U2V FOREIGN KEY(STUDY_AREA_ID) REFERENCES STUDY_AREA(ID) ;

ALTER TABLE PROFESSOR_REGISTEREDTCCS
    ADD CONSTRAINT FKQ2H2V1FJIGCBY2GMXJUSCL8KP FOREIGN KEY(REGISTEREDTCCS_ID) REFERENCES TCC(ID) ;

ALTER TABLE STUDENT_INTERESTED_STUDY_AREAS
    ADD CONSTRAINT FK7TDYG97AMREE2B40A1SW9U99J FOREIGN KEY(STUDENT_ID) REFERENCES STUDENT(ID) ;

ALTER TABLE PROFESSOR_LABS
    ADD CONSTRAINT FKTAC37U55JIGWT4P2JPEWK6882 FOREIGN KEY(PROFESSOR_ID) REFERENCES PROFESSOR(ID) ;

ALTER TABLE TCC_INTERESTED_PROFESSORS
    ADD CONSTRAINT FK19P1Y8OJAH1MUPP5N3ES5BUSF FOREIGN KEY(PROFESSOR_ID) REFERENCES PROFESSOR(ID) ;

ALTER TABLE TCCMATCH_USER_EMAILS
    ADD CONSTRAINT FKNRWIUVCQKSHDL168K0W4BSUGQ FOREIGN KEY(TCCMATCH_USER_ID) REFERENCES TCCMATCH_USER(ID) ;

ALTER TABLE STUDENT
    ADD CONSTRAINT FKE7VNOJBLQ466E89P0BINKUC5I FOREIGN KEY(TCC_ID) REFERENCES TCC(ID) ;

ALTER TABLE TCC_INTERESTED_STUDENTS
    ADD CONSTRAINT FKMTV12OT8I1ANDB772SSLYC00E FOREIGN KEY(TCC_ID) REFERENCES TCC(ID) ;

ALTER TABLE STUDENT
    ADD CONSTRAINT FKEIQ7A06F3JQU2FB5LAGUOGPXC FOREIGN KEY(ID) REFERENCES TCCMATCH_USER(ID) ;

ALTER TABLE TCC
    ADD CONSTRAINT FKD3PTQ6PYVOBA45EKS3JELJHI3 FOREIGN KEY(ADVISOR_ID) REFERENCES PROFESSOR(ID) ;

ALTER TABLE PROFESSOR
    ADD CONSTRAINT FKRKDB5WLWHQX4HTQJD81G52PDL FOREIGN KEY(ID) REFERENCES TCCMATCH_USER(ID) ;

ALTER TABLE ADMIN
    ADD CONSTRAINT FK5J7H7V5KHD6DPPKEFET7TIC6P FOREIGN KEY(ID) REFERENCES TCCMATCH_USER(ID) ;

ALTER TABLE TCC
    ADD CONSTRAINT FKB7RI1NIOFH3RY28BYO0XR954R FOREIGN KEY(ADVISED_STUDENT_ID) REFERENCES STUDENT(ID) ;

ALTER TABLE PROFESSOR_REGISTEREDTCCS
    ADD CONSTRAINT FKO5J1FS5VF9JL7R1OCY3G9QEFF FOREIGN KEY(PROFESSOR_ID) REFERENCES PROFESSOR(ID) ;

ALTER TABLE PROFESSOR_INTERESTED_STUDY_AREAS
    ADD CONSTRAINT FKNIWRUW77XJTWJYOQCW7IH2GSK FOREIGN KEY(PROFESSOR_ID) REFERENCES PROFESSOR(ID) ;

ALTER TABLE PROFESSOR_INTERESTED_STUDY_AREAS
    ADD CONSTRAINT FKJM88TNPPO0GFBIVXD3A6MIJAC FOREIGN KEY(STUDY_AREA_ID) REFERENCES STUDY_AREA(ID);
