ALTER TABLE ADMIN ADD CONSTRAINT CONSTRAINT_3 PRIMARY KEY(ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ADMIN;

ALTER TABLE ORIENTATION_INTEREST ADD CONSTRAINT CONSTRAINT_E PRIMARY KEY(ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ORIENTATION_INTEREST;

ALTER TABLE ORIENTATION_ISSUE ADD CONSTRAINT CONSTRAINT_E8 PRIMARY KEY(ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ORIENTATION_ISSUE;

ALTER TABLE ORIENTATION_PROPOSAL ADD CONSTRAINT CONSTRAINT_8 PRIMARY KEY(ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ORIENTATION_PROPOSAL;

ALTER TABLE PROFESSOR ADD CONSTRAINT CONSTRAINT_6 PRIMARY KEY(ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PROFESSOR;

ALTER TABLE STUDENT ADD CONSTRAINT CONSTRAINT_B PRIMARY KEY(ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.STUDENT;

-- 0 +/- SELECT COUNT(*) FROM PUBLIC.STUDENT_INTERESTED_STUDY_AREAS;

ALTER TABLE STUDY_AREA ADD CONSTRAINT CONSTRAINT_2 PRIMARY KEY(ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.STUDY_AREA;

ALTER TABLE TCC ADD CONSTRAINT CONSTRAINT_1 PRIMARY KEY(ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TCC;

ALTER TABLE TCCMATCH_USER ADD CONSTRAINT CONSTRAINT_C PRIMARY KEY(ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TCCMATCH_USER;

ALTER TABLE TCCPROPOSAL ADD CONSTRAINT CONSTRAINT_8B PRIMARY KEY(ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TCCPROPOSAL;

-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TCCPROPOSAL_STUDY_AREAS;
ALTER TABLE PROFESSOR_ORIENTEDTCCS ADD CONSTRAINT UK_NDJK9WP8H0L8YI04I3PHEX9X UNIQUE(ORIENTEDTCCS_ID);
ALTER TABLE PROFESSOR_INTERESTEDTCCS ADD CONSTRAINT UK_R286TXHWDQT8QM4EXRA9UMQ5J UNIQUE(INTERESTEDTCCS_ID);
ALTER TABLE ORIENTATION_INTEREST ADD CONSTRAINT FKQUOPIMYMENTFW8ONUBBSAQWN2 FOREIGN KEY(INTERESTEDTCC_ID) REFERENCES TCC(ID) ;
ALTER TABLE TCC ADD CONSTRAINT FK1VP63KO2DWT6S6V1JHXCOLH7B FOREIGN KEY(PROFESSOR_ID) REFERENCES PROFESSOR(ID) ;
ALTER TABLE TCCPROPOSAL ADD CONSTRAINT FKILIV2G65E5WBUR7WLOE3OLPBP FOREIGN KEY(STUDENT_ID) REFERENCES STUDENT(ID) ;
ALTER TABLE PROFESSOR_ORIENTEDTCCS ADD CONSTRAINT FKG81FQREO5NW159PE5TUKJGGI2 FOREIGN KEY(PROFESSOR_ID) REFERENCES PROFESSOR(ID) ;
ALTER TABLE ORIENTATION_ISSUE ADD CONSTRAINT FK84F9BGXRSGLRM30PFJMKB7R0B FOREIGN KEY(STUDENT_ID) REFERENCES STUDENT(ID);
ALTER TABLE TCCPROPOSAL_STUDY_AREAS ADD CONSTRAINT FKQCXO5XGNKJBIQTR22YET9QC8T FOREIGN KEY(TCCPROPOSAL_ID) REFERENCES TCCPROPOSAL(ID) ;
ALTER TABLE ORIENTATION_ISSUE ADD CONSTRAINT FKPUPU6PN14WAOS05YNI6OOVG7N FOREIGN KEY(TCC_ID) REFERENCES TCC(ID);
ALTER TABLE PROFESSOR_INTERESTEDTCCS ADD CONSTRAINT FKAL6527JR7JXUKHKJP8NV5T0P0 FOREIGN KEY(PROFESSOR_ID) REFERENCES PROFESSOR(ID);
ALTER TABLE STUDENT_INTERESTED_STUDY_AREAS ADD CONSTRAINT FK2M9QWOB07JNNPYRHAG6S22U2V FOREIGN KEY(STUDY_AREA_ID) REFERENCES STUDY_AREA(ID) ;
ALTER TABLE PROFESSOR_INTERESTEDTCCS ADD CONSTRAINT FKNMM06B0J2Q25AQBFAVWYV65XH FOREIGN KEY(INTERESTEDTCCS_ID) REFERENCES ORIENTATION_PROPOSAL(ID) ;
ALTER TABLE STUDENT_INTERESTED_STUDY_AREAS ADD CONSTRAINT FK7TDYG97AMREE2B40A1SW9U99J FOREIGN KEY(STUDENT_ID) REFERENCES STUDENT(ID) ;
ALTER TABLE ORIENTATION_PROPOSAL ADD CONSTRAINT FKTQG070MHBRJB4BAFPD4CLCSLR FOREIGN KEY(INTERESTED_PROFESSOR_ID) REFERENCES PROFESSOR(ID) ;
ALTER TABLE PROFESSOR_LABS ADD CONSTRAINT FKTAC37U55JIGWT4P2JPEWK6882 FOREIGN KEY(PROFESSOR_ID) REFERENCES PROFESSOR(ID) ;
ALTER TABLE PROFESSOR_ORIENTEDTCCS ADD CONSTRAINT FKP2M1B32OCYH9ULC1YFE9BE6O2 FOREIGN KEY(ORIENTEDTCCS_ID) REFERENCES TCC(ID) ;
ALTER TABLE TCC ADD CONSTRAINT FKK2AJUL40GLHINM8MD7UH07SJF FOREIGN KEY(ID) REFERENCES TCCPROPOSAL(ID) ;
ALTER TABLE TCCPROPOSAL_STUDY_AREAS ADD CONSTRAINT FKEFVFOWSIAQ80DM93JD018WSVU FOREIGN KEY(STUDY_AREAS_ID) REFERENCES STUDY_AREA(ID) ;
ALTER TABLE STUDENT ADD CONSTRAINT FKE7VNOJBLQ466E89P0BINKUC5I FOREIGN KEY(TCC_ID) REFERENCES TCC(ID) ;
ALTER TABLE ORIENTATION_INTEREST ADD CONSTRAINT FK1BG3EB4O55RK1QJC85754WTRN FOREIGN KEY(INTERESTED_STUDENT_ID) REFERENCES STUDENT(ID) ;
ALTER TABLE STUDENT ADD CONSTRAINT FKEIQ7A06F3JQU2FB5LAGUOGPXC FOREIGN KEY(ID) REFERENCES TCCMATCH_USER(ID) ;
ALTER TABLE PROFESSOR ADD CONSTRAINT FKRKDB5WLWHQX4HTQJD81G52PDL FOREIGN KEY(ID) REFERENCES TCCMATCH_USER(ID) ;
ALTER TABLE ADMIN ADD CONSTRAINT FK5J7H7V5KHD6DPPKEFET7TIC6P FOREIGN KEY(ID) REFERENCES TCCMATCH_USER(ID) ;
ALTER TABLE ORIENTATION_PROPOSAL ADD CONSTRAINT FKOD3X3HHBH4DFR8H6JE3QJOWPC FOREIGN KEY(INTERESTED_PROPOSAL_ID) REFERENCES TCCPROPOSAL(ID) ;
ALTER TABLE PROFESSOR_INTERESTED_STUDY_AREAS ADD CONSTRAINT FKNIWRUW77XJTWJYOQCW7IH2GSK FOREIGN KEY(PROFESSOR_ID) REFERENCES PROFESSOR(ID) ;
ALTER TABLE PROFESSOR_INTERESTED_STUDY_AREAS ADD CONSTRAINT FKJM88TNPPO0GFBIVXD3A6MIJAC FOREIGN KEY(STUDY_AREA_ID) REFERENCES STUDY_AREA(ID) ;
